name: sunemoji
version: '1.1'
main: io.github.skuffy808.sunemoji.Sunemoji
api-version: '1.21'
authors: [ Skuffy ]
description: A simple emoji plugin made for the sunset Minecraft server

commands:
  emojis:
    description: Lists all emojis.
    usage: /<command>
    permission: sunemoji.emojis

permissions:
  sunemoji.emojis:
    description: Allows the use of /emojis command
    default: op
  sunemoji.use:
    description: Allows the use of the emoji replacement
    default: op
